services:
  - type: web
    name: auron-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: 8705540280:AAE-BuiH4biFKdgE8loJpFiTAcYBXw7hydw
        sync: false
      - key: postgresql://auron_db_user:vqXMcb9SQ3k6JCX3Dj00DttbhorYm3fq@dpg-d81h5n7lk1mc73adicbg-a/auron_db
        sync: false
      - key: ADMIN_ID
        value: "8276815852"
      - key: CHANNEL_USERNAME
        value: "@Auron_search"
      - key: BOT_USERNAME
        value: "Auronsearchesbot"
      - key: CHECK_SUBSCRIPTION
        value: "True"
      - key: FREE_LIMIT
        value: "10"
      - key: MAX_REF_BONUS
        value: "20"
      - key: USDT_WALLET
        value: "TQ1hHPveZ737G5i1ZxHN2sfpV9PSdx5nfV"
      - key: PORT
        value: "8080"
    healthCheckPath: /healservices:
  - type: web
    name: auron-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: 8705540280:AAE-BuiH4biFKdgE8loJpFiTAcYBXw7hydw
        sync: false
      - key: postgresql://auron_db_user:vqXMcb9SQ3k6JCX3Dj00DttbhorYm3fq@dpg-d81h5n7lk1mc73adicbg-a/auron_db
        sync: false
      - key: ADMIN_ID
        value: "8276815852"
      - key: CHANNEL_USERNAME
        value: "@Auron_search"
      - key: BOT_USERNAME
        value: "Auronsearchesbot"
      - key: CHECK_SUBSCRIPTION
        value: "True"
      - key: FREE_LIMIT
        value: "10"
      - key: MAX_REF_BONUS
        value: "20"
      - key: USDT_WALLET
        value: "TQ1hHPveZ737G5i1ZxHN2sfpV9PSdx5nfV"
      - key: PORT
        value: "8080"
    healthCheckPath: /health
